[package]
name = "kdtree"
version = "0.3.0"
authors = ["mrhooray <ruihu.pvt@gmail.com>"]
description = "K-dimensional tree in Rust for fast geospatial indexing"
keywords = ["tree", "nearest", "dimension", "search", "geo"]
readme = "README.md"
repository = "https://github.com/mrhooray/kdtree-rs"
documentation = "http://mrhooray.github.io/kdtree-rs/kdtree/index.html"
license = "MIT"

[dev-dependencies]
rand = "~0.3.9"
